/*
 * video_capture.cpp
 *
 * Captures video frames from a V4L2 camera and publishes them on the
 * "ovidds_frames" DDS topic using the zzdds C++ bindings.
 *
 * Ported from the OpenDDS version.  The main structural differences are:
 *
 *  - Participant creation: TheParticipantFactoryWithArgs()    →  generated DDS::DomainParticipantFactory
 *  - TypeSupport: FrameTypeSupportImpl::register_type()       →  ovidds::FrameTypeSupport::register_type()
 *  - Entity creation (topic/pub/dw): via C ABI (C++ create_* also works; nullptr QoS uses defaults)
 *  - Listener base: LocalObject<DDS::DataWriterListener>      →  DDS::DataWriterListenerBase
 *  - Data field: frame.data.length(n) / .length()             →  frame.data.resize(n) / .size()
 *  - Primitive types: CORBA::Long                             →  int32_t
 *
 * Note on entity creation: create_topic / create_publisher / create_datawriter have
 * field-by-field QoS adaptation generated by zidl (both in- and out-direction, D3).
 * We still call them via the C ABI with nullptr QoS for simplicity; default QoS works
 * fine for the demo.  get_qos / set_qos are now fully implemented via D3.
 *
 * No camera / no display in CI: if the real camera fails to open (or
 * OVIDDS_MOCK_CAMERA is set), this falls back to a synthetic frame source
 * (a cycling solid color plus a frame-number overlay, not real video) instead
 * of exiting -- enough to exercise the full DDS write path deterministically
 * without hardware. OVIDDS_RUN_SECONDS bounds the run for CI instead of
 * waiting on an interactive stdin line.
 */

#include <opencv2/highgui.hpp>
#include <opencv2/imgproc.hpp>
#include <opencv2/videoio.hpp>

#include <atomic>
#include <chrono>
#include <cstdlib>
#include <iostream>
#include <sstream>
#include <thread>

// dcps_impl.hpp pulls in dcps.hpp (abstract C++ interfaces), dcps.h (C ABI),
// zzdds_c.h (factory + helpers), and defines the concrete Impl classes and
// ListenerBridge base classes.
#include "dcps_impl.hpp"
#include "zzdds_cpp.hpp"

// Generated by: zidl -b cpp --generate-zzdds-wrappers -o <dir> ovidds.idl
// Declares ovidds::Frame, ovidds::FrameDataWriter, ovidds::FrameTypeSupport.
#include "ovidds.hpp"

#include "ovidds_common.h"

using namespace cv;

namespace {

constexpr int MOCK_WIDTH  = 640;
constexpr int MOCK_HEIGHT = 480;

bool env_flag(const char* name) {
    const char* v = std::getenv(name);
    return v && *v && std::string(v) != "0";
}

// Positive integer env var, or 0 if unset/invalid.
int env_seconds(const char* name) {
    const char* v = std::getenv(name);
    if (!v || !*v) return 0;
    const int n = std::atoi(v);
    return n > 0 ? n : 0;
}

// Fills an existing frame buffer in place (ref_frame is a non-owning Mat view
// over ovidds::Frame::data -- never reallocated) with a deterministic,
// cheap-to-generate pattern: a solid color that cycles with frame_index, plus
// a text overlay showing the frame number so a human watching a headful
// consumer can tell frames are actually changing.
void generate_mock_frame(Mat& ref_frame, uint64_t frame_index) {
    ref_frame = Scalar(static_cast<uint8_t>((frame_index * 2) % 256),
                        static_cast<uint8_t>((frame_index * 3) % 256),
                        static_cast<uint8_t>((frame_index * 5) % 256));
    putText(ref_frame, "mock frame " + std::to_string(frame_index), Point(10, 30),
            FONT_HERSHEY_SIMPLEX, 0.8, Scalar(255, 255, 255), 2);
}

} // namespace

// ── DataWriter listener ───────────────────────────────────────────────────────

class FrameWriterListener : public DDS::DataWriterListenerBase {
public:
    explicit FrameWriterListener(std::atomic<bool>& connected) : connected_(connected) {}

    void on_publication_matched(std::shared_ptr<::DDS::DataWriter> /*writer*/,
                                ::DDS::PublicationMatchedStatus status) override {
        std::cout << "FrameWriterListener::on_publication_matched() current_count="
                  << status.current_count << std::endl;
        connected_.store(status.current_count != 0);
    }

    void on_offered_deadline_missed(std::shared_ptr<::DDS::DataWriter> /*writer*/,
                                    ::DDS::OfferedDeadlineMissedStatus /*status*/) override {
        std::cout << "FrameWriterListener::on_offered_deadline_missed()" << std::endl;
    }

    void on_offered_incompatible_qos(std::shared_ptr<::DDS::DataWriter> /*writer*/,
                                     ::DDS::OfferedIncompatibleQosStatus /*status*/) override {
        std::cout << "FrameWriterListener::on_offered_incompatible_qos()" << std::endl;
    }

    void on_liveliness_lost(std::shared_ptr<::DDS::DataWriter> /*writer*/,
                            ::DDS::LivelinessLostStatus /*status*/) override {
        std::cout << "FrameWriterListener::on_liveliness_lost()" << std::endl;
    }

private:
    std::atomic<bool>& connected_;
};

// ── Write thread ──────────────────────────────────────────────────────────────

// capture == nullptr means "no real camera": frames come from generate_mock_frame
// at a fixed MOCK_WIDTH x MOCK_HEIGHT instead of whatever the device reports.
static void write_thread(const std::atomic<bool>& run,
                         const std::atomic<bool>& connected,
                         DDS_DataWriter           raw_dw,
                         VideoCapture*            capture)
{
    ovidds::FrameDataWriter frame_dw(raw_dw);

    std::stringstream ss;
    size_t thread_id;
    ss << std::this_thread::get_id() << std::flush;
    ss >> thread_id;
    std::cout << "Writer thread ID: '" << ss.str()
              << "' read as size_t: 0x" << std::hex << thread_id << std::dec << std::endl;

    ovidds::Frame frame{};
    frame.source_id = static_cast<int32_t>(thread_id);
    std::cout << "Using frame source ID: 0x" << std::hex << frame.source_id << std::dec << std::endl;

    (void)frame_dw.register_instance(frame);

    size_t frame_depth = 3;
    uint64_t frames_written = 0;
    const auto stats_start = std::chrono::steady_clock::now();
    auto last_stats_at = stats_start;

    while (run.load()) {
        if (!connected.load()) {
            std::this_thread::sleep_for(std::chrono::milliseconds(50));
            continue;
        }

        const int32_t old_size_x = frame.size_x;
        const int32_t old_size_y = frame.size_y;

        if (capture) {
            frame.size_x = static_cast<int32_t>(capture->get(CAP_PROP_FRAME_WIDTH));
            frame.size_y = static_cast<int32_t>(capture->get(CAP_PROP_FRAME_HEIGHT));
        } else {
            frame.size_x = MOCK_WIDTH;
            frame.size_y = MOCK_HEIGHT;
        }

        if (frame.type == 0 || frame.size_x != old_size_x || frame.size_y != old_size_y) {
            if (capture) {
                Mat temp;
                *capture >> temp;
                frame.type = temp.type();
                frame_depth = temp.elemSize();
            } else {
                frame.type = CV_8UC3;
                frame_depth = 3;
            }
        }

        const size_t frame_buffer_size =
            static_cast<size_t>(frame.size_x) * static_cast<size_t>(frame.size_y) * frame_depth;

        if (frame.data.size() != frame_buffer_size) {
            if (frame.data.empty()) {
                std::cout << "Setting up frame for the first time: " << std::flush;
            } else {
                std::cout << "Frame dimensions differ from previous frame, reconfiguring: " << std::flush;
            }
            std::cout << "type=" << frame.type
                      << " width=" << frame.size_x
                      << " height=" << frame.size_y
                      << " depth=" << frame_depth << std::endl;
            frame.data.resize(frame_buffer_size);
        }

        Mat ref_frame(frame.size_y, frame.size_x, frame.type, frame.data.data());
        if (capture) {
            *capture >> ref_frame;
        } else {
            generate_mock_frame(ref_frame, frame.count);
            // Emulate a real camera's frame pacing instead of spinning as
            // fast as possible and flooding the DDS writer.
            std::this_thread::sleep_for(std::chrono::milliseconds(33));
        }

        ++frame.count;

        if (ref_frame.cols > 3840 || ref_frame.rows > 2160) {
            std::cout << "Frame dimensions " << ref_frame.cols << "x" << ref_frame.rows
                      << " exceed UHD (3840x2160), skipping." << std::endl;
            continue;
        }

        int rc;
        do {
            rc = frame_dw.write(frame);
        } while (connected.load() && rc == DDS_RETCODE_TIMEOUT);

        if (rc != DDS_RETCODE_OK) {
            std::cerr << "Failed to write frame (rc=" << rc << ")" << std::endl;
        } else {
            ++frames_written;
        }

        // Periodic (not per-frame) stats -- every 5s, cheap enough not to
        // flood CI logs but still gives a clear "still alive and writing"
        // signal for the acceptance check below.
        const auto now = std::chrono::steady_clock::now();
        if (now - last_stats_at >= std::chrono::seconds(5)) {
            const auto elapsed = std::chrono::duration_cast<std::chrono::duration<double>>(now - stats_start).count();
            std::cout << "stats: wrote " << frames_written << " frames in "
                      << elapsed << "s" << std::endl;
            last_stats_at = now;
        }
    }

    frame_dw.unregister_instance(frame);
    std::cout << "video_capture: wrote " << frames_written << " frames total." << std::endl;
}

// ── main ──────────────────────────────────────────────────────────────────────

int main(int /*argc*/, char** /*argv*/)
{
    auto factory = zzdds::create_factory();
    if (!factory) {
        std::cerr << "Failed to create factory." << std::endl;
        return 1;
    }
    auto participant = factory->create_participant(
        static_cast<uint32_t>(DOMAIN), ::DDS::DomainParticipantQos{}, nullptr, 0);
    if (!participant) {
        std::cerr << "Failed to create participant." << std::endl;
        return 1;
    }
    DDS_DomainParticipant raw_part = participant->native_handle();

    // D3: get_qos now has out-direction C→C++ adaptation — quick sanity check.
    {
        ::DDS::DomainParticipantQos qos{};
        if (participant->get_qos(qos) == DDS_RETCODE_OK)
            std::cout << "Participant user_data size (default): " << qos.user_data.value.size() << std::endl;
    }

    // A1: register_type now uses the IDL-scoped name "ovidds::Frame" by default.
    // A2: ovidds::FrameTypeSupport is now namespace-qualified (was ovidds_FrameTypeSupport).
    if (ovidds::FrameTypeSupport::register_type(raw_part, FRAME_TYPE_NAME) != 0) {
        std::cerr << "Failed to register Frame type." << std::endl;
        return 1;
    }

    // A3: string params are now const char* — no more const_cast needed here.
    DDS_Topic topic = DDS_DomainParticipant_create_topic(
        raw_part, FRAME_TOPIC_NAME, FRAME_TYPE_NAME, nullptr, nullptr, 0);
    if (!topic) {
        std::cerr << "Failed to create topic." << std::endl;
        return 1;
    }

    DDS_Publisher publisher = DDS_DomainParticipant_create_publisher(
        raw_part, nullptr, nullptr, 0);
    if (!publisher) {
        std::cerr << "Failed to create publisher." << std::endl;
        return 1;
    }

    // A 640x480x3 Frame is ~900KB, fragmented into hundreds of RTPS/UDP
    // datagrams. Under the default BEST_EFFORT reliability, a single dropped
    // fragment silently loses the whole sample (no full reassembly, ever) --
    // confirmed by testing: shrinking Frame to a few bytes (no fragmentation
    // needed) delivers fine even at BEST_EFFORT, while full-size frames only
    // ever arrive with RELIABLE. Not a zzdds bug, just the wrong QoS default
    // for a payload this size.
    DDS_DataWriterQos dw_qos{};
    DDS_Publisher_get_default_datawriter_qos(publisher, &dw_qos);
    dw_qos.reliability.kind = DDS_ReliabilityQosPolicyKind_RELIABLE_RELIABILITY_QOS;

    std::atomic<bool> connected{false};
    // B3: FrameWriterListener now subclasses DDS::DataWriterListenerBase (from dcps.hpp).
    // Callbacks now receive shared_ptr<DDS::DataWriter> instead of raw DDS_DataWriter.
    auto listener = std::make_shared<FrameWriterListener>(connected);
    DDS_DataWriterListener c_listener = listener->c_listener();

    DDS_DataWriter raw_dw = DDS_Publisher_create_datawriter(
        publisher, topic, &dw_qos, &c_listener, DDS_PUBLICATION_MATCHED_STATUS);
    if (!raw_dw) {
        std::cerr << "Failed to create datawriter." << std::endl;
        return 1;
    }

    VideoCapture capture;
    bool use_mock = env_flag("OVIDDS_MOCK_CAMERA");
    if (!use_mock) {
        constexpr int deviceID = 0;
        constexpr int apiID    = cv::CAP_V4L2;
        if (!capture.open(deviceID, apiID) || !capture.isOpened()) {
            std::cout << "No camera available -- falling back to a synthetic mock frame source."
                      << std::endl;
            use_mock = true;
        }
    } else {
        std::cout << "OVIDDS_MOCK_CAMERA set -- using a synthetic mock frame source." << std::endl;
    }

    if (!use_mock) {
        if (!capture.set(CAP_PROP_FRAME_HEIGHT, MOCK_HEIGHT))
            std::cerr << "Warning: cannot set height to " << MOCK_HEIGHT << std::endl;
        if (!capture.set(CAP_PROP_FRAME_WIDTH, MOCK_WIDTH))
            std::cerr << "Warning: cannot set width to " << MOCK_WIDTH << std::endl;
    }

    std::atomic<bool> run{true};
    std::thread writer(write_thread, std::cref(run), std::cref(connected), raw_dw,
                       use_mock ? nullptr : &capture);

    const int run_seconds = env_seconds("OVIDDS_RUN_SECONDS");
    if (run_seconds > 0) {
        std::cout << "OVIDDS_RUN_SECONDS=" << run_seconds
                  << " set -- running for a bounded duration instead of waiting on stdin." << std::endl;
        std::this_thread::sleep_for(std::chrono::seconds(run_seconds));
    } else {
        std::string line;
        std::getline(std::cin, line);
    }
    run.store(false);

    writer.join();

    participant->delete_contained_entities();
    factory->delete_participant(participant);

    return 0;
}
